name: Build Push NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: org-runner
    steps:
      - uses: actions/checkout@v1
      - name: Set job env
        run: |
          setJobEnv
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm test
      - run: npm publish
